# 菜单配置（若不需要某项可直接删除）
menu:
  # 首页
  - id: home
    link: /
    icon: home
    class: menu-home
  #乐评  
  - id: reviews
    link: /categories/reviews/
    icon: book 
    class: menu-archives
  #照片
  - id: photos
    link: /categories/photos/
    icon: camera  
    class: menu-archives
  # 归档
#  - id: archives
#    link: /archives
#    icon: archive
#    class: menu-archive
  # 目录
  - id: category
    link: javascript:;
    category: true
    icon: bookmark
    class: menu-category
  # 读书
  - id: Albums
    link: /albums
    icon: music
    class: menu-reading
  # 关于
#  - id: about
#    link: /about
#    icon: user
#    class: menu-about
  # 搜索

# 颜色配置
color:
  header: grey darken-4
  footer: grey darken-4
  page_nav: grey darken-4
  side_nav: grey darken-3
  tag: indigo lighten-1
  article_title_link: light-blue
  link: light-blue
  pagination: light-blue
  tab: light-blue
  archive_item: grey
  fab: light-blue
  fab_2: light-blue
  fab_3: light-blue lighten-1
  new: light-blue
  about_header: grey darken-4
  about_title: light-blue

archive_yearly: true

# 版权信息
copyright: © 2018 本站为歌迷所建与音乐人无关，所有原创文章版权所有

# Disqus评论shortname，若为空则不启用
disqus_shortname:
# 多说shortname，若为空则不启用
duoshuo_shortname:
# 网易云跟帖productKey，从通用代码中获取，若为空则不启用
yungentie_product_key:

# Google分析track id，若为空则不启用
google_analytics:
# 腾讯分析sId，若为空则不启用
tencent_analytics:

# 高亮的主题，若为空则使用默认主题
google_code_prettify: prettify-tomorrow-night-eighties

# 是否启用MathJax数学公式渲染。如果你确认整个站点的博文都不会用到Latex数学公式，可以将其该项设为false提高页面加载速度
mathjax: true

# 是否启用网页计数器（使用不蒜子插件）
page_stat: false